### ISSUE TITLE
context is null while retrieving drizzle.contracts

### ISSUE THREAD

**Issue by kongzhe607** [trufflesuite/drizzle-react#11]
According to the README.md, drizzle.contracts can be retrieved for the constructor of React.Component, like below

```
    constructor(props, context) {
        super(props)
        console.log("Loading test", context)
    }
```

However, I wrote the jsx code like this, the context in DrizzleProvider and HomeContainer prints out undefined.
```
ReactDOM.render(
    <DrizzleProvider options={options}>
        <Provider store={store}>
            <LoadingContainer>
                <Router history={history}>
                    <Route path="/" component={App}>
                        <IndexRoute component={LoginForKPCContainer} />
                    </Route>
                </Router>
            </LoadingContainer>
        </Provider>
    </DrizzleProvider>,
    document.getElementById('root')
);
```

Did I make some mistake? Anyone can help?

**Comment by m-b-davis** [comment]
This had me too - the devil is in the details. What you need to do is first make sure your component has contextTypes configured:

// At the bottom of your component's file

```
MyComponent.contextTypes = {
  drizzle: PropTypes.object
}

export default MyComponent;
```


store the reference in the constructor: 

```
class MyComponent extends Component {
    constructor(props, context) {
        super(props)
        // this will be undefined at this point
        this.contracts = console.log("Loading test", context)
    }
...
```

Then, this.contracts only receives a value **after** drizzleStatus.initialised = true. So make sure you check drizzleStatus before accessing contracts.

**Comment by sklingler93** [comment]
Is there are reason that `contextTypes` does not include `drizzle` in `drizzleConnect.js`? Seems like it should be part of the HOC and passed in via props

**Comment by paulsoh** [comment]
@m-b-davis thanks... works like a charm
