### ISSUE TITLE
TypeError: Cannot read property 'block' of undefined

### ISSUE THREAD

**Issue by artemarta** [trufflesuite/drizzle-react#13]
Everything has been done according to official docs.
But I've got an error. 
I think it's because in https://github.com/trufflesuite/drizzle-react/blob/master/src/DrizzleProvider.js on line 29 there is no check whether **web3** property exists on **options** object.

I have the following code:
```
import Token from './contracts/StandardToken.json';

export const drizzleOptions = {
    contracts: [Token],
};
```
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { DrizzleProvider } from 'drizzle-react';
import { initializeIcons } from '@uifabric/icons';
import { Fabric } from 'office-ui-fabric-react/lib/Fabric';
import { store } from './store';
import { AppRouter } from './router';
import { unregister as unregisterServiceWorker } from './registerServiceWorker';
import { drizzleOptions } from './drizzleOptions';

import './index.css';

initializeIcons();

const withProvider = WrappedComponent => (
    <Fabric>
        <DrizzleProvider options={drizzleOptions}>
            <Provider store={store}>
                <WrappedComponent />
            </Provider>
        </DrizzleProvider>
    </Fabric>
);

ReactDOM.render(withProvider(AppRouter), document.getElementById('root'));
unregisterServiceWorker();
```

**Comment by sklingler93** [comment]
Same issue here, got it working thanks to @artemarta by adding `web3.block` to my options:
``` 
web3: {
    block: false
}
```
I'm not sure what the use-case is for `block` and I couldn't find anything in the docs about it, but I'm thinking `web3` should be null checked

**Comment by wangki** [comment]
@sklingler93 That doesn't work for me. My option 
`web3: {
        block: false,
        fallback: {
            type: "ws",
            url: "ws://127.0.0.1:7545"
        }
    }`

**Comment by wangki** [comment]
add `polls: {},` works perfect. what happened here?

Refer to : https://github.com/trufflesuite/drizzle/issues/32

**Comment by DiscRiskandBisque** [comment]
This is caused by a combination of things that have now been patched:
* The options checks were assuming some key existence, now `drizzle` comes with sensible default options as of [release v1.1.4](https://github.com/trufflesuite/drizzle/releases/tag/1.1.4).
* The `block` options this is checking for was vestigial and should have been removed, it now is as of `drizzle-react` [release v1.1.1](https://github.com/trufflesuite/drizzle-react/releases/tag/1.1.1).
