### ISSUE TITLE
Provide non-minified code and/or source maps via npm

### ISSUE THREAD

**Issue by nharlow89** [trufflesuite/drizzle-react#14]
I am not familiar with the npm publishing process, but I have noticed that all of the drizzle packages on npm are published with a single minified js file. This has made it very inconvenient and sometimes difficult to debug things. Exceptions caught by drizzle are unreadable and tools like React Dev Tools do not show the actual component names.

**Comment by adrianmcli** [comment]
@nharlow89 Does #35 sufficiently solve the problem for you? If so, I will merge it.

P.S. Thanks to @shershen08 for submitting PR #35.
