### ISSUE TITLE
Access contract data in render() method

### ISSUE THREAD

**Issue by mi-kas** [trufflesuite/drizzle-react#21]
When I am setting the reference to the contracts in the constructor like this:
`constructor(props, context) {
    super(props)
    this.contracts = context.drizzle.contracts
}`

and then trying to accessing contract data in the render() function like below, I alway get the error message of "initializeDrizzle TypeError: this.contracts.SimpleStorage.methods.storedData.data is not a function"
`var storedData = this.props.drizzleStatus.initialized ? this.contracts.SimpleStorage.methods.storedData.data() : 'Loading...'`

Whats the correct way to access data in the render() method?

**Comment by svechinsky** [comment]
Hi could you please elaborate on your solution?

**Comment by dangell7** [comment]
Same

**Comment by bertiespell** [comment]
same!

**Comment by dangell7** [comment]
Try call().call() or send().send()
