### ISSUE TITLE
Access the actual web3 Instance

### ISSUE THREAD

**Issue by vertangelx** [trufflesuite/drizzle-react#22]
I am using the `drizzle` trufflebox and need to perform something using the `web3` instance, like

    this.props.web3.eth.getBalance(address)

Using this

	const mapStateToProps = state => {
	  return {
	    drizzleStatus: state.drizzleStatus,
	    web3: state.web3
	  }
	}

we are only able to get the `status` string from `this.props.web3`, not the `web3` instance itself.

Any ideas on how we can expose/access the actual `web3` instance?

**Comment by DalderupMaurice** [comment]
It's undefined as the constructor is hit before web3 exists :P @mi-kas

**Comment by mi-kas** [comment]
Not if you use a [Loading Component](https://github.com/trufflesuite/drizzle-react#recipe-loading-component)
