### ISSUE TITLE
Can't write sagas which depend on instance of Drizzle when using DrizzleProvider

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/drizzle-react#24]
I'm trying to find a way to use Drizzle in my own redux sagas while also using `DrizzleProvider` but coming up short.

The problem is, how do I pass an instance of drizzle to my own sagas? It looks like `DrizzleProvider` creates its `Drizzle` instance in [`getChildContext`](https://github.com/trufflesuite/drizzle-react/blob/master/src/DrizzleProvider.js#L23), and there's no handy way to fish it back out.

A workaround might be to create a container component which fetches it from the context and then kicks off the root saga, but this feels a bit hacky. Perhaps it should be possible to supply an instance of `Drizzle` to the `DrizzleProvider`?

**Comment by sklingler93** [comment]
I'm using my own version of `DrizzleProvider` in which I've changed `getChildContext` to the following:
```js
  getChildContext() {
    const store = this.props.store ? this.props.store : generateStore(this.props.options)
    const drizzle = this.props.drizzle || new Drizzle(this.props.options, store)
    return { drizzle, store };
  }
```

Then in my `generateStore` I initialize drizzle and set the saga context:
```js
  const drizzle = new Drizzle(drizzleOptions, store);

  sagaMiddleware.run(rootSaga);
  sagaMiddleware.setContext({
    drizzle
  });
```

And in my render function I pass the drizzle instance to `DrizzleProvider`:
```js
const { store, drizzle } = generateStore();

render(
  <DrizzleProvider store={ store } drizzle={ drizzle }>
      <App/>
  </DrizzleProvider>,
  document.getElementById('root')
);
```

I do think this would be a super useful feature in Drizzle!

**Comment by BryceDoganer** [comment]
I am also looking to use this feature and while I like the second option better, I'm worried about changing the module and later updating and breaking the application. 

So, I decided to go with the container option above, but I needed to connect the container with `drizzleConnect() `before it would work: 

```
import React, { Component, Children } from 'react';
import PropTypes from 'prop-types';

import { drizzleConnect } from 'drizzle-react'

class DrizzleSagaConnector extends Component {
  constructor(props, context) {
    super(props)
    this.props.sagaMiddleware.run(
      this.props.rootSaga,
      context.drizzle
    );
  }
  render() {
    return Children.only(this.props.children)
  }
}

DrizzleSagaConnector.contextTypes = {
  drizzle: PropTypes.object
}

export default drizzleConnect(DrizzleSagaConnector)
```

**Comment by mi-kas** [comment]
Is there maybe a better way of using Drizzle in sagas with the new Context API (see PR [https://github.com/trufflesuite/drizzle-react/pull/28](https://github.com/trufflesuite/drizzle-react/pull/28))?

**Comment by adrianmcli** [comment]
@mi-kas I haven't looked into the whole sagas part of Drizzle quite yet. Do you have any ideas on this?
