### ISSUE TITLE
Problem updating from store

### ISSUE THREAD

**Issue by j4m3sb0mb** [trufflesuite/drizzle-react#27]
I've noticed some problems updating components, It usually works but sometimes doesn't and updates all on the next operation.
I'm doing something wrong? do you have the same problem?

**Comment by adrianmcli** [comment]
Needs more context here, but the DrizzleStore should update with the latest data automatically. If it sounds like it's an issue with `drizzleConnect`, I recommend you use the new React Context API instead.
