### ISSUE TITLE
Connecting to multiple drizzle providers

### ISSUE THREAD

**Issue by yahgwai** [trufflesuite/drizzle-react#30]
I want to create an react/drizzle app that can deploy/call contracts on 2 different web3 providers eg. A local private network and metamask. An example use case would be a statechannel where the app would deploy contracts to both the mainnet and the private chain. State updates would take place on the private chain, passing these updates between participants for countersignature, then at some point the latest state would be flushed back to mainnet.

Is there any way to do this?

As a first attempt I altered the drizzle options to allow me to directly inject a web3 provider. I then made two drizzle instances, each with their own store, these worked well and I was able to observe changes in them due to transactions issued on both networks. The problem I encountered was connecting components to the store via react-redux, which only expects there to be one store per application.

Any ideas? And should I be asking this in the drizzle repo, rather than drizzle-react?

**Comment by adrianmcli** [comment]
@yahgwai I think you should be able to do this with the new React Context API. Closing for now just to clean up the issue backlog.
