### ISSUE TITLE
Uncaught at initializeDrizzle TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by hashoshi** [trufflesuite/drizzle-react#31]
I am getting this error: "uncaught at initializeDrizzle TypeError: Cannot read property 'apply' of undefined" while trying to start up my drizzle app.

The contract ABI is getting passed in successfully and I have made sure the contract is referenced in Drizzle Options. I'm baffled as to why this is happening. Please advise. I can provide any other info as necessary

<img width="543" alt="screen shot 2018-08-26 at 1 51 25 pm" src="https://user-images.githubusercontent.com/33706156/44631233-2ee73580-a937-11e8-8214-307f1214c902.png">

**Comment by adrianmcli** [comment]
This sounds like a problem from the ContractData component in Drizzle-React-Components: https://github.com/trufflesuite/drizzle-react-components/blob/master/src/ContractData.js

I recommend making an issue over there instead.
