### ISSUE TITLE
Error while using a different network

### ISSUE THREAD

**Issue by monosux** [trufflesuite/drizzle-react#37]
Hi,
I have an issue. If I switch metamask to a different network (not where the contract is loaded) I get an error:

`
uncaught at root at root  
at contractsSaga  
at takeEvery  
at addContract  
at instantiateContract  
TypeError: Cannot read property 'address' of undefined`

How can I catch this error and do not show an error in a console?

**Comment by soundyogi** [comment]
how can we access the sagas in general?
the old non-react 16.3 context version wont work anymore with an existing redux store
+1
