### ISSUE TITLE
drizzle-react-components v16.3+

### ISSUE THREAD

**Issue by parkinsonj** [trufflesuite/drizzle-react#38]
Hi drizzle-react team,

I have just submitted a [PR](https://github.com/trufflesuite/drizzle-react-components/pull/37) on drizzle-react-components to provide an implementation compatible with the v16.3+ API documented here (the existing implementations use the legacy standard).

However, the maintainer for that repository has not updated anything for a month now -- there is an ever growing list of PRs and issues going unresolved. Do you have any way of contacting them or adding a few more people to maintain the library?

**Comment by soundyogi** [comment]
+1

**Comment by adrianmcli** [comment]
That PR has been merged.
