### ISSUE TITLE
Export Context

### ISSUE THREAD

**Issue by epiqueras** [trufflesuite/drizzle-react#44]
This should be exported.

https://github.com/trufflesuite/drizzle-react/blob/5ce024822d74a9d7926f1182bedb51be42869bef/src/DrizzleContext.js#L3

It is useful for many things. Like React's new `useContext` hook for example.

**Comment by yidongw** [comment]
I Agree. If the context is not exported. In order to use the context in react lifecycle method, we have to pass the context to its child prop. We can't use Class.contextType, which is a easier way to achieve it

**Comment by epiqueras** [comment]
@yidongw You can use https://github.com/trufflesuite/drizzle-react/blob/master/src/DrizzleProvider.js for that.

**Comment by yidongw** [comment]
DrizzleProvider is using a Context API that will be removed in [future react release](https://reactjs.org/docs/legacy-context.html)

**Comment by epiqueras** [comment]
@yidongw 
Then use this provider https://github.com/trufflesuite/drizzle-react/blob/5ce024822d74a9d7926f1182bedb51be42869bef/src/DrizzleContext.js#L43

It also works with Class.contextType.

**Comment by yidongw** [comment]
How? Provider is a component. According to https://reactjs.org/docs/context.html?no-cache=1#dynamic-context, themed-button.js session, you have to import the context first

**Comment by epiqueras** [comment]
Oh you are right, I was thinking about the legacy API where you can define
contextType manually.

**Comment by adrianmcli** [comment]
fixed by #47

**Comment by wmitsuda** [comment]
Any ETA for next release? The React 16.8 with hooks were just released, and this seems to be a blocker for the useContext use case. At least any chance of backporting this small fix to an intermediate release?

**Comment by adrianmcli** [comment]
@wmitsuda sure, we'll try to make a release this week.
