### ISSUE TITLE
Make available cached web3.eth functions, like getBlockNumber

### ISSUE THREAD

**Issue by Garoth** [trufflesuite/drizzle-react#49]
As far as I can tell, there is no way to get Drizzle's internal current block number. In general, there's no system in Drizzle for caching web3.eth functions -- only direct contract calls. As a result, my app would call the regular getBlockNumber constantly. Turns out half my app's eth data usage is this getBlockNumber call

It's simple enough for me to implement a cache myself, but this would ideally be part of Drizzle

**Comment by adrianmcli** [comment]
@Garoth Can you make this issue under the Drizzle [repo](https://github.com/trufflesuite/drizzle) instead?

**Comment by adrianmcli** [comment]
Closing for now, but happy to continue discussion in the other repo.

**Comment by Garoth** [comment]
Done -> https://github.com/trufflesuite/drizzle/issues/166
