### ISSUE TITLE
Warning: MyComponent defines an invalid contextType. contextType should point to the Context object returned by React.createContext(). Did you accidentally pass the Context.Consumer instead?

### ISSUE THREAD

**Issue by kombos** [trufflesuite/drizzle-react#57]
I'm using the follow DrizzleContext Provider and Consumer objects in my DApp code: 
Provider:: 
```
<DrizzleContext.Provider drizzle={drizzle}>
                <App />
</DrizzleContext.Provider>
```

Consumer::
```
export default () => (
    <DrizzleContext.Consumer>
        {(drizzleContext) => {
....
....
}
```

I'm deriving context object in some components as such: 
```
class Header extends React.Component {
    static contextType = DrizzleContext.Consumer;

    constructor(props, context) {
        super(props);
        this.context = context;
  }
```

Recently it has started throwing the following warning: 
`Warning: MyComponent defines an invalid contextType. contextType should point to the Context object returned by React.createContext(). Did you accidentally pass the Context.Consumer instead?`

Any ideas how to deal with this? please mention if possible the right way to get context object in Components. Tx.

**Comment by adrianmcli** [comment]
@kombos It looks like you're mixing the old context API with the new context API. We do not use `contextType` with the new context API. You'll have to follow these [instructions](https://github.com/trufflesuite/drizzle-react#using-the-react-context-api-for-react-v163) for a better usage example.

**Comment by kombos** [comment]
I did read the instructions but they only talk about providing context object to the top most level (app). Could you please tell me how we could bring context to nested components? for example: 
in case i have a component at nested level:  
`<app/> ==> <PageSection/> ==> <Container/> ==> <Component/> ==> <MicroComponent/>.
`now, if i need to bring context reference (eg. web3 object) to <MicroComponent/>, would i have to pass on 'drizzle' object from <App/> all the way to <MicroComponent/> ??

**Comment by adrianmcli** [comment]
You only need to wrap your `MicroComponent` with the Consumer component, and basically inject `drizzle` from there. This is the new Context API pattern, I suggest you have a read with the official React [docs](https://reactjs.org/docs/context.html).

**Comment by kombos** [comment]
The only query i have left is how do I use it on a 'Class' component, since Consumer component takes a function component as child? 
In the link that you shared of official React docs, it talks about ['Class.contextType'](https://reactjs.org/docs/context.html#classcontexttype) . Do we have something of that sort for DrizzleContext ? What I had used above is similar to what the new React Context API docs have stated: 
class Header extends React.Component {
   ```
 static contextType = DrizzleContext.Consumer;

    constructor(props, context) {
        super(props);
        this.context = context;
  }
```

**Comment by adrianmcli** [comment]
If you don't want to use the function as a child pattern, you can grab the actual context directly like this:

```js
import { DrizzleContext } from "drizzle-react"

class Header extends React.Component {
  static contextType = DrizzleContext.Context

  render() {
    const { drizzle, drizzleState, initialized } = this.context
    return <div>{/* ... */}</div>
  }
}
```

As an aside, there was a brief discussion about this here: https://github.com/trufflesuite/drizzle-react/pull/47

**Comment by kombos** [comment]
@adrianmcli , I tried using `static contextType = DrizzleContext.Context;` but it don't seem to work properly. the `drizzleState` object I tried to derive has the value undefined. Could this be a problem with the `drizzle-react` version? Im currently using 1.2.0

**Comment by adrianmcli** [comment]
@kombos Oh it looks like we haven't done a release with the new features! Thanks for looking into this, we will do a release this week. If you can't wait, then I would suggest that you wrap the component with the `DrizzleContext.Consumer` and allow your component to consume the necessary variables via props.

**Comment by kombos** [comment]
thanks a lot. would be waiting for the release :) . And meanwhile will use `DrizzleContext.Consumer` like you mentioned.

**Comment by adrianmcli** [comment]
@kombos we just did a release. Can you test out the `Class.contextType` pattern with the new release?

**Comment by kombos** [comment]
> @kombos we just did a release. Can you test out the `Class.contextType` pattern with the new release?

sure, will update you soon.

**Comment by kombos** [comment]
I tried the following variations after updating to 1.3.0, and here are the results: 

```js
import { DrizzleContext } from "drizzle-react"

class Header extends React.Component {
  static contextType = DrizzleContext.Context

  render() {
    const { drizzle, drizzleState, initialized } = this.context
    return <div>{/* ... */}</div>
  }
}
```
Result: same Warning Statement + Error (context not received)

```js
import { DrizzleContext } from "drizzle-react"

class Header extends React.Component {
  static contextType = DrizzleContext.Consumer

  render() {
    const { drizzle, drizzleState, initialized } = this.context
    return <div>{/* ... */}</div>
  }
}
```
Result:Warning statement thrown, but context is received. 

```js
import { DrizzleContext } from "drizzle-react"

class Header extends React.Component {
  static contextType = DrizzleContext

  render() {
    const { drizzle, drizzleState, initialized } = this.context
    return <div>{/* ... */}</div>
  }
}
```
Result: same Warning Statement + Error (context not received)

```js
import { DrizzleContext } from "drizzle-react"

class Header extends React.Component {

  render() {
    const { drizzle, drizzleState, initialized } = this.context
    return <div>{/* ... */}</div>
  }
}

Header.contextType = DrizzleContext
```
Result: same Warning Statement + Error (context not received)

**Comment by adrianmcli** [comment]
@kombos I encountered a similar problem before realizing that I forgot to wrap my top-level component with the context provider. For example:

```js
// In my top level App.js file
<DrizzleContext.Provider drizzle={drizzle}>
  <MyComponent />
</DrizzleContext.Provider>
```

Did you make sure to do that?

**Comment by kombos** [comment]
> @kombos I encountered a similar problem before realizing that I forgot to wrap my top-level component with the context provider. For example:
> 
> ```js
> // In my top level App.js file
> <DrizzleContext.Provider drizzle={drizzle}>
>   <MyComponent />
> </DrizzleContext.Provider>
> ```
> 
> Did you make sure to do that?

hi @adrianmcli , 
yes I'm already passing both Provider and Consumer as such: 
_my index.js:_ 
```
ReactDOM.render(
    (
        <ThemeProvider theme={theme}>
            <DrizzleContext.Provider drizzle={drizzle}>
                <App />
            </DrizzleContext.Provider>
        </ThemeProvider>

    ), document.getElementById('root'),
);
```

_my app.js is:_ 
```
export default () => (
    <DrizzleContext.Consumer>
        {(drizzleContext) => {
...
...

}
    </DrizzleContext.Consumer>
);
```
the component in question which is throwing the warning (header.js or NotificationBar.js) is rendered inside app.js.

**Comment by adrianmcli** [comment]
@kombos I've made a working example here: https://github.com/adrianmcli/drizzle-react-usage-example

**Comment by kombos** [comment]
seem to be working now ! ... the Warnings are also gone and the context object is received using DrizzleContext.Context. I had to delete my node_modules folder and re-run npm install, and it started working.

**Comment by adrianmcli** [comment]
Ah yes, that's the only way to make sure you are using the latest version. Can we close this issue again now?

**Comment by kombos** [comment]
Sure. Closing this issue. Thanks again.
