### ISSUE TITLE
DrizzleContext.Consumer is there a way to differentiate between a web3 provider being available and loading?

### ISSUE THREAD

**Issue by dannycarrera** [trufflesuite/drizzle-react#62]
In the legacy drizzleConnect, there was a way to differentiate between your dApp loading and if a web3 provider was completely missing. This was demonstrated in drizzle-react-components. With the new DrizzleContext, it seems we can only check if DrizzleContext is initialized. Is there a way to be able to show both a loading screen or a "No web3 provider" error page?

Thanks!

**Comment by adrianmcli** [comment]
I believe this is also a concern with Drizzle. Let me investigate this further. This might be related to EIP-1193, as @cds-amal has clued me into.
