### ISSUE TITLE
New version of React ?

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/drizzle-react#67]
Hi

The version of React bundled with drizzle-react (16.4.2) has been released on August 2018. Since then, a lot updates have been released (bug fixed, improvement, new features).

Is there any reason to keep using an older version of react drizzle-react?

Thanks

**Comment by adrianmcli** [comment]
Yeah it should actually be a `peerDependency`. We're actually thinking about moving everything into a monorepo this week. So I'll have to put this on hold for now but we can keep this issue open. Thanks for starting the discussion.

**Comment by socialcode-rob1** [comment]
Does the same go for react-redux?

Version 5.0.7 and earlier of react-redux performed the following validation on the component passed to connect:

https://github.com/reduxjs/react-redux/blob/v5.0.7/src/components/connectAdvanced.js#L91

```js
    invariant(
      typeof WrappedComponent == 'function',
      `You must pass a component to the function returned by ` +
      `${methodName}. Instead received ${JSON.stringify(WrappedComponent)}`
    )
```

With the introduction of React.forwardRef and other features introduced in React 16.8 (hooks), it is possible to have a component type that is not a function.

More recent versions of react-redux instead use isValidElementType from the react-is package. This correctly recognizes the component types returned by forwardRef and other methods.
